### ISSUE TITLE
Invalidate events stored in the database once they are completed.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#19]

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I do not wish to be informed on events in the past.](https://trello.com/c/Wtbbkup6/164-as-a-user-i-do-not-wish-to-be-informed-on-events-in-the-past)

**Comment by liuche** [comment]
Closed by #64
