### ISSUE TITLE
Match up yelp IDs to Google Places IDs.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#26]

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I can see photos pulled from Google Places so I see nice images not taken from yelp.](https://trello.com/c/JuCDYAcE/159-as-a-user-i-can-see-photos-pulled-from-google-places-so-i-see-nice-images-not-taken-from-yelp)

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see a wide variety of sources, not reliant on the Crosswalk API](https://trello.com/c/y6dODMMJ/134-as-a-user-i-want-to-see-a-wide-variety-of-sources-not-reliant-on-the-crosswalk-api)

**Comment by liuche** [comment]
I assume that this is mainly for photos, so I'm going to close this issue. There isn't space in the UI for other content (like reviews) but if we decide to include more varied content, let's reopen this issue.
