### ISSUE TITLE
Pull images from the Google Places API.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#27]

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I can see photos pulled from Google Places so I see nice images not taken from yelp.](https://trello.com/c/JuCDYAcE/159-as-a-user-i-can-see-photos-pulled-from-google-places-so-i-see-nice-images-not-taken-from-yelp)

**Comment by liuche** [comment]
After investigating this, the Google APIs return entire pngs so unless we want to store and serve these images, we don't want to use this. Each photo also requires two API calls. In the future if we want to use this, we'd need to host (not sure about the ToC).
