### ISSUE TITLE
Inconsistent timestamp formats for events

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox-server#53]
Events that are pulled from Eventful have a date format of `yyyy-MM-dd'T'HH:mm:ss` and those coming from the google calendars have a date format of `yyyy-MM-dd'T'HH:mm:ssz` 

As these are local times, a date format of `yyyy-MM-dd'T'HH:mm:ss` would make sense as we don't need the timezone

**Comment by liuche** [comment]
Handled by #56 .
