### ISSUE TITLE
Get missing hours for businesses returned from Yelp "search businesses"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/prox-server#61]
Using Yelp's search/ API doesn't return hours for the businesses. Pull #59 makes hours optional, but we should make the extra Yelp API call to fetch the full business object that contains hours.

**Comment by jhugman** [comment]
We already do. We do get factual data, but that's more unreliable than yelp.

**Comment by liuche** [comment]
To clarify, this is in the event code, where we try to ensure that a business is present for each event. The event code uses Yelp2 APIs which don't contain hours, so we would need to make another call to the Yelp3 business/ API to get a biz object that contains hours, once we have the Yelp id, and then pass that to researchPlaces to get a more complete biz object.

**Comment by jhugman** [comment]
This is addressed in https://github.com/mozilla-mobile/prox-server/pull/63
