### ISSUE TITLE
Crawl script makes recursive subdivisions if we cannot retrieve all places

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox-server#87]
So we can retrieve *all* the places.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prox shows all places that I find on Yelp around me](https://trello.com/c/p2e8Ecwh/362-prox-shows-all-places-that-i-find-on-yelp-around-me)

**Comment by thebnich** [comment]
Fixed by #87.
